### ISSUE TITLE
Clarifying the license

### ISSUE THREAD

**Issue by jamesmortensen** [Marak/The-Git-Rap#6]
Just FYI, this is awesome!  Our team loves the Git Rap. :)  Many of our team members have recently learned the command line, so many of the commands listed in the song are things they can relate to strongly.  Thanks for being so passionate about programming to actually sit down and do something like this. It's one of the things that makes me enjoy being a developer!

In the song, the lyrics do imply it's okay to fork this and do stuff with it, but we were wondering if a more formal license could be added to this repository.  The song is basically somewhat satirical, so we'd hate to violate implicit copyright by assuming that forking was okay. :)

Would you mind adding a license?  Perhaps a permissive license like BSD or MIT or the Apache Commons or Creative Commons license?  Thank you!

**Comment by Marak** [comment]
Awesome!

I added a Creative Common license for the project.

Hopefully this will be permissive enough, let me know.

http://creativecommons.org/licenses/by-nc/3.0/
https://github.com/Marak/The-Git-Rap/blob/master/LICENSE
